# Generated by Django 4.0.3 on 2022-10-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='no value', max_length=256)),
                ('number', models.IntegerField(default=1)),
                ('password', models.CharField(default='no value', max_length=20)),
                ('companyName', models.CharField(default='no value', max_length=100)),
                ('proofOfBiz_link', models.CharField(default='no value', max_length=500)),
                ('category', models.CharField(default='no value', max_length=40)),
                ('loc_firstLine', models.CharField(default='no value', max_length=200)),
                ('loc_secondLine', models.CharField(default='no value', max_length=200)),
                ('loc_pincode', models.IntegerField(default=1)),
                ('isAgreementAccpeted', models.BooleanField(default=False)),
                ('isAdminVerified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='no value', max_length=256)),
                ('number', models.IntegerField(default=1)),
                ('password', models.CharField(default='no value', max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
